### ISSUE TITLE
How to apply Pagination based on scrolling

### ISSUE THREAD

**Issue by ShaikhKabeer** [sussol/react-native-data-table#16]
Does anybody knows how to apply pagination to react-native-data-table based on scrolling ? It's needed so please help.

**Comment by Chris-Petty** [comment]
There is no built in pagination in react-native-data-table, not generally expected in a mobile app as far as I am aware.

If your DB API has pagination, you could could use state in your app screen (that displays the table) to pass different paginated data into the table. Implement buttons on the screen (i.e. in the view that contains the table) interacting with the page number/data.

**Comment by Chris-Petty** [comment]
@ShaikhKabeer comment if I've misinterpreted. If you effectively want to request more data from a API as the user scrolls, that isn't supported either - this is just a bunch of useful tools that adapt ListView as a table. So that dataSource works much like the input of ListView (which more or less expects all it's data upfront).

Could be a good idea in the future though.
